weather_year_1941_3H:
  snapshots:
    start: 1941-07-01 00:00
    end: 1942-06-30 23:00
    inclusive: both
  atlite:
    default_cutout: europe-1941-1946-era5
    cutouts:
      europe-1941-1946-era5:
        prepare_kwargs:
          module: era5
          x:
          - -12.0
          - 35.0
          y:
          - 33.0
          - 72
          dx: 0.25
          dy: 0.25
          time:
          - '1941'
          - '1942'
  renewable:
    onwind:
      cutout: europe-1941-1946-era5
    offwind-ac:
      cutout: europe-1941-1946-era5
    offwind-dc:
      cutout: europe-1941-1946-era5
    offwind-float:
      cutout: europe-1941-1946-era5
    solar:
      cutout: europe-1941-1946-era5
    solar-hsat:
      cutout: europe-1941-1946-era5
    hydro:
      cutout: europe-1941-1946-era5
  solar_thermal:
    cutout: europe-1941-1946-era5
  sector:
    heat_demand_cutout: europe-1941-1946-era5
  lines:
    dynamic_line_rating:
      cutout: europe-1941-1946-era5
  clustering:
    temporal:
      resolution_sector: 3H

